{{- if and .Values.secrets.external.enabled (not .Values.secrets.manual.enabled) }}

{{- /* 1. APP SECRET */ -}}
{{- $appSecretName := .Values.envFromSecret | default (printf "%s-secret" (include "momo-radio.fullname" .)) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $appSecretName }}
  labels:
    {{- include "momo-radio.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStoreName }}
    kind: {{ .Values.secrets.external.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ $appSecretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.external.appSecretRef | default .Values.secrets.external.remoteRef }}

{{- /* 2. INFRA CONFIG SECRET */ -}}
{{- if .Values.secrets.external.infraSecretRef }}
---
{{- $infraSecretName := index .Values.envFromSecrets 0 | default (printf "%s-infra-config" (include "momo-radio.fullname" .)) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $infraSecretName }}
  labels:
    {{- include "momo-radio.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStoreName }}
    kind: {{ .Values.secrets.external.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ $infraSecretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.external.infraSecretRef }}
{{- end }}
{{- end }}
