{{- if and .Values.secrets.external.enabled (not .Values.secrets.manual.enabled) }}
{{- $secretName := .Values.envFromSecret | default (first .Values.envFromSecrets | default (printf "%s-secret" (include "momo-radio.fullname" .))) -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "momo-radio.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStoreName }}
    kind: {{ .Values.secrets.external.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ $secretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.external.remoteRef | default .Values.secrets.external.appSecretRef }}
{{- end }}