{{- if and .Values.secrets.external.enabled (not .Values.secrets.manual.enabled) }}

{{- /* 1. APP SECRET */ -}}
{{- $appSecretName := (printf "%s-secret" (include "momo-radio.fullname" .)) -}}
{{- if and .Values.envFromSecrets (gt (len .Values.envFromSecrets) 1) -}}
  {{- $appSecretName = index .Values.envFromSecrets 1 -}}
{{- else if .Values.envFromSecret -}}
  {{- $appSecretName = .Values.envFromSecret -}}
{{- end -}}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $appSecretName }}
  labels:
    {{- include "momo-radio.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.external.refreshInterval | default "1h" | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.external.secretStoreName }}
    kind: {{ .Values.secrets.external.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ $appSecretName }}
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ .Values.secrets.external.appSecretRef | default .Values.secrets.external.remoteRef }}
{{- end }}