{{- if .Values.apiIngress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "momo-radio.fullname" . }}-api
  labels:
    {{- include "momo-radio.labels" . | nindent 4 }}
  {{- with .Values.apiIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.apiIngress.className }}
  {{- if .Values.apiIngress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.apiIngress.host | quote }}
      secretName: {{ .Values.apiIngress.tls.secretName }}
  {{- end }}
  rules:
    - host: {{ .Values.apiIngress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "momo-radio.fullname" . }}-server
                port:
                  number: {{ .Values.server.port }}
{{- end }}