{{- if .Values.secrets.manual.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.envFromSecret }}
  labels:
    {{- include "momo-radio.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- toYaml .Values.secrets.manual.data | nindent 2 }}
{{- end }}