apiVersion: v2
name: momo-radio
description: Radio streaming service design for music makers
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/sudo-bngz/momo-radio-api/main/logo.png
home: https://github.com/sudo-bngz/momo-radio-helm
sources:
  - https://github.com/sudo-bngz/momo-radio
keywords:
  - radio
  - streaming
  - ffmpeg
  - hls
  - keda
  - saas
maintainers:
  - name: momo
    email: hello@momosbasement.com